# Generated by Django 3.1.3 on 2021-03-06 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='type',
            new_name='operation_type',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='date',
            new_name='pub_date',
        ),
    ]
